# CSV File code
crawl.html.code=crawl.html
crawl.data.code=crawl.data

# Database Config
database.username=root
database.password=230503

database.control=jdbc:mysql://localhost:3306/control
database.staging=jdbc:mysql://localhost:3306/staging
database.datawarehouse=jdbc:mysql://localhost:3306/dw

# Sending Email
email.host=smtp.gmail.com
email.port=587
email.username=imdungx@gmail.com
email.password=illl xptv fuuy tbhm

# Email Notify Content
ttc.subject.error=Module dw-temp-to-clean error
ttc.subject.success=Module dw-temp-to-clean success
ttc.content.error.less-than-2=Notify from dw-temp-to-clean module: Need to crawl file/save to staging.cp_daily first!
ttc.content.error.more-than-2=Notify from dw-temp-to-clean module: Data has been cleaned already!
ttc.content.error.clean-failed=Notify from dw-temp-to-clean module: Preprocessing data from cp_daily to data_cleaning failed!
ttc.content.error.log-failed=Notify from dw-temp-to-clean module: Create log status failed!
ttc.content.success.log-success=Notify from dw-temp-to-clean module: Create log status successfully!