# CSV File code
crawl.html.code=crawl.html
crawl.data.code=crawl.data

# Database Config
database.username=root
database.password=230503

database.control=jdbc:mysql://localhost:3306/control
database.staging=jdbc:mysql://localhost:3306/staging
database.datawarehouse=jdbc:mysql://localhost:3306/dw

# Sending Email
email.host=smtp.gmail.com
email.port=587
email.username=imdungx@gmail.com
email.password=illl xptv fuuy tbhm

# Email Notify Content
ctd.subject.error=Module dw-clean-to-dim error
ctd.subject.success=Module dw-clean-to-dim success
ctd.content.error.less-than-3=Notify from dw-clean-to-dim module: Need to crawl file or Save to staging.cp_daily or Clean data first!
ctd.content.error.more-than-3=Notify from dw-clean-to-dim module: Data has been saved to database dw already!
ctd.content.error.transform-failed=Notify from dw-clean-to-dim module: Transform data from data_cleaning to dim table failed!
ctd.content.error.log-failed=Notify from dw-clean-to-dim module: Create log status failed!
ctd.content.success.log-success=Notify from dw-clean-to-dim module: Create log status successfully!